/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tpv_yongdayang_ndkdemo_JniUtil */

#ifndef _Included_com_tpv_yongdayang_ndkdemo_JniUtil
#define _Included_com_tpv_yongdayang_ndkdemo_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tpv_yongdayang_ndkdemo_JniUtil
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_tpv_yongdayang_ndkdemo_JniUtil_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
